// packages/create-mullion/templates/next/ui/minimal/src/components/QueryInput.tsx
'use client';

import {useCallback} from 'react';
import type {KeyboardEvent} from 'react';

interface QueryInputProps {
  value: string;
  onChange: (value: string) => void;
  onSubmit?: () => void;
  label?: string;
  placeholder?: string;
  rows?: number;
  loading?: boolean;
  submitLabel?: string;
}

export function QueryInput({
  value,
  onChange,
  onSubmit,
  label = 'Query',
  placeholder = 'Enter your query...',
  rows = 3,
  loading = false,
  submitLabel = 'Submit',
}: QueryInputProps) {
  const handleKeyDown = useCallback(
    (event: KeyboardEvent<HTMLTextAreaElement>) => {
      if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
        event.preventDefault();
        if (value.trim() && !loading && onSubmit) {
          onSubmit();
        }
      }
    },
    [loading, onSubmit, value],
  );

  const handleClick = () => {
    if (value.trim() && !loading && onSubmit) {
      onSubmit();
    }
  };

  return (
    <div className="query-input stack-sm">
      {label ? <label className="m-0">{label}</label> : null}
      <textarea
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        rows={rows}
        className="w-full"
        onKeyDown={handleKeyDown}
      />
      <div className="flex items-center justify-between gap-md">
        <span className="text-sm text-muted">
          Press <kbd>Cmd</kbd>+<kbd>Enter</kbd> to submit
        </span>
        <button
          type="button"
          className="btn btn-primary"
          disabled={loading || !value.trim()}
          onClick={handleClick}
        >
          {loading ? <span className="loading" /> : null}
          {loading ? 'Processing...' : submitLabel}
        </button>
      </div>
    </div>
  );
}

// packages/create-mullion/templates/nuxt/ui/shadcn/app/components/QueryInput.vue
<script setup lang="ts">
/**
 * QueryInput Component (Nuxt UI)
 *
 * A text input component for queries using Nuxt UI Textarea and Button.
 */

defineOptions({
  name: 'QueryInput',
});

const props = withDefaults(
  defineProps<{
    modelValue: string;
    placeholder?: string;
    label?: string;
    rows?: number;
    loading?: boolean;
    submitLabel?: string;
  }>(),
  {
    placeholder: 'Enter your query...',
    label: 'Query',
    rows: 3,
    loading: false,
    submitLabel: 'Submit',
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  submit: [];
}>();

const inputValue = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
});

const handleSubmit = () => {
  if (inputValue.value.trim() && !props.loading) {
    emit('submit');
  }
};

const handleKeydown = (event: KeyboardEvent) => {
  if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
    handleSubmit();
  }
};
</script>

<template>
  <div class="query-input space-y-3">
    <UFormField v-if="label" :label="label">
      <UTextarea
        v-model="inputValue"
        :placeholder="placeholder"
        :rows="rows"
        autoresize
        class="w-full"
        @keydown="handleKeydown"
      />
    </UFormField>
    <UTextarea
      v-else
      v-model="inputValue"
      :placeholder="placeholder"
      :rows="rows"
      autoresize
      class="w-full"
      @keydown="handleKeydown"
    />

    <div class="flex items-center justify-between">
      <span class="text-sm text-muted">
        Press <UKbd>Cmd</UKbd>+<UKbd>Enter</UKbd> to submit
      </span>
      <UButton
        :loading="loading"
        :disabled="loading || !inputValue.trim()"
        @click="handleSubmit"
      >
        {{ loading ? 'Processing...' : submitLabel }}
      </UButton>
    </div>
  </div>
</template>
