// packages/create-mullion/templates/next/ui/minimal/src/components/ResultCard.tsx
'use client';

import type {ReactNode} from 'react';

interface ResultCardProps {
  title?: string;
  loading?: boolean;
  error?: string | null;
  show?: boolean;
  children?: ReactNode;
}

export function ResultCard({
  title,
  loading = false,
  error,
  show = true,
  children,
}: ResultCardProps) {
  if (!show) return null;

  return (
    <div className={`result-card card ${error ? 'border-error' : ''}`.trim()}>
      {title ? (
        <div className="card-header flex items-center justify-between">
          <h3 className="card-title text-base">{title}</h3>
          {loading ? <span className="loading" /> : null}
        </div>
      ) : null}

      <div className="card-body">
        {error ? (
          <div className="text-error">
            <strong>Error:</strong> {error}
          </div>
        ) : null}
        {children}
      </div>
    </div>
  );
}

// packages/create-mullion/templates/nuxt/ui/shadcn/app/components/ResultCard.vue
<script setup lang="ts">
/**
 * ResultCard Component (Nuxt UI)
 *
 * A card component for displaying results using Nuxt UI Card.
 */

defineOptions({
  name: 'ResultCard',
});

withDefaults(
  defineProps<{
    title?: string;
    loading?: boolean;
    error?: string | null;
  }>(),
  {
    title: 'Result',
    loading: false,
    error: null,
  },
);
</script>

<template>
  <UCard class="result-card">
    <template #header>
      <div class="flex items-center justify-between">
        <h3 class="text-base font-semibold">{{ title }}</h3>
        <UIcon v-if="loading" name="i-lucide-loader-circle" class="animate-spin" />
      </div>
    </template>

    <!-- Error state -->
    <UAlert
      v-if="error"
      color="error"
      variant="soft"
      icon="i-lucide-alert-triangle"
      :title="error"
    />

    <!-- Loading state -->
    <div v-else-if="loading" class="flex items-center gap-2 text-muted">
      <UIcon name="i-lucide-loader-circle" class="animate-spin" />
      <span>Processing...</span>
    </div>

    <!-- Content slot -->
    <template v-else>
      <slot />
    </template>

    <!-- Footer slot -->
    <template v-if="$slots.footer" #footer>
      <slot name="footer" />
    </template>
  </UCard>
</template>
