// packages/create-mullion/templates/next/ui/minimal/src/components/ResultCard.tsx
'use client';

import type {ReactNode} from 'react';

interface ResultCardProps {
  title?: string;
  loading?: boolean;
  error?: string | null;
  show?: boolean;
  children?: ReactNode;
}

export function ResultCard({
  title,
  loading = false,
  error,
  show = true,
  children,
}: ResultCardProps) {
  if (!show) return null;

  return (
    <div className={`result-card card ${error ? 'border-error' : ''}`.trim()}>
      {title ? (
        <div className="card-header flex items-center justify-between">
          <h3 className="card-title text-base">{title}</h3>
          {loading ? <span className="loading" /> : null}
        </div>
      ) : null}

      <div className="card-body">
        {error ? (
          <div className="text-error">
            <strong>Error:</strong> {error}
          </div>
        ) : null}
        {children}
      </div>
    </div>
  );
}

// packages/create-mullion/templates/nuxt/ui/minimal/app/components/ResultCard.vue
<script setup lang="ts">
/**
 * ResultCard Component
 *
 * A reusable card component for displaying results with optional metadata.
 */

defineOptions({
  name: 'ResultCard',
});

withDefaults(
  defineProps<{
    title?: string;
    loading?: boolean;
    error?: string | null;
  }>(),
  {
    title: 'Result',
    loading: false,
    error: null,
  },
);
</script>

<template>
  <div class="result-card card" :class="{ 'border-error': error }">
    <div v-if="title" class="card-header flex items-center justify-between">
      <h3 class="card-title text-base">{{ title }}</h3>
      <span v-if="loading" class="loading" />
    </div>

    <div class="card-body">
      <!-- Error state -->
      <div v-if="error" class="flex items-start gap-sm text-error">
        <span aria-hidden="true">!</span>
        <span>{{ error }}</span>
      </div>

      <!-- Loading state -->
      <div v-else-if="loading" class="flex items-center gap-sm text-muted">
        <span class="loading" />
        <span>Processing...</span>
      </div>

      <!-- Content slot -->
      <template v-else>
        <slot />
      </template>
    </div>

    <!-- Footer slot for actions or metadata -->
    <div v-if="$slots.footer" class="card-footer">
      <slot name="footer" />
    </div>
  </div>
</template>
